In [3]:
#Question 1
import numpy as np
array1 = np.array([1, 2, 3, 0])
array2 = np.array([4, 1, 0, 6])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [5 3 3 6]
Subtraction: [-3  1  3 -6]
Multiplication: [4 2 0 0]
Division: [0.25 2.    inf 0.  ]


C:\Users\DELL\AppData\Local\Temp\ipykernel_11648\3176386855.py:9: RuntimeWarning: divide by zero encountered in divide
  division = array1 / array2


In [5]:
#Question 2
array1 = np.random.randint(1, 101, size=5)

array2 = np.random.randint(1, 101, size=(4, 5))

addition = array2 + array1  
subtraction = array2 - array1 
print("Array 1 (1-D):", array1)
print("Array 2 (2-D):")
print(array2)
print("Addition (Array 2 + Array 1):")
print(addition)
print("Subtraction (Array 2 - Array 1):")
print(subtraction)

Array 1 (1-D): [63 64 18 22 32]
Array 2 (2-D):
[[34 69 33 90 62]
 [11 58 82 23 70]
 [67 37 11 99 73]
 [24 13 28 76 15]]
Addition (Array 2 + Array 1):
[[ 97 133  51 112  94]
 [ 74 122 100  45 102]
 [130 101  29 121 105]
 [ 87  77  46  98  47]]
Subtraction (Array 2 - Array 1):
[[-29   5  15  68  30]
 [-52  -6  64   1  38]
 [  4 -27  -7  77  41]
 [-39 -51  10  54 -17]]


In [7]:
#Question 3a
array_3d = np.random.random((3, 3, 3))

third_column_second_2d = array_3d[1, :, 2] 
print("3-D Array (3x3x3):")
print(array_3d)
print("Third column of the second 2-D array:")
print(third_column_second_2d)


3-D Array (3x3x3):
[[[0.66267756 0.96103059 0.06521822]
  [0.98543878 0.05830041 0.23013437]
  [0.64260884 0.55691682 0.0749693 ]]

 [[0.93600087 0.785107   0.60603619]
  [0.33378112 0.19343639 0.97064832]
  [0.29002454 0.34082944 0.44290514]]

 [[0.85124685 0.86647328 0.93316347]
  [0.43053086 0.07466155 0.10268768]
  [0.53162834 0.10559096 0.06496233]]]
Third column of the second 2-D array:
[0.60603619 0.97064832 0.44290514]


In [9]:
#Question 3b
array_3d = np.random.random((3, 3, 3))

first_and_third_rows_first_2d = array_3d[0, [0, 2], :] 

print("3-D Array (3x3x3):")
print(array_3d)
print("First and third rows of the first 2-D array:")
print(first_and_third_rows_first_2d)

3-D Array (3x3x3):
[[[0.09316685 0.64826447 0.83727574]
  [0.93594669 0.47784566 0.69118365]
  [0.84070875 0.07653612 0.35842223]]

 [[0.30147464 0.50164118 0.85156766]
  [0.50902383 0.10766956 0.83494621]
  [0.287584   0.07380752 0.10301882]]

 [[0.97119028 0.53721442 0.9182556 ]
  [0.2018533  0.49251918 0.46241413]
  [0.36656839 0.47117279 0.9947933 ]]]
First and third rows of the first 2-D array:
[[0.09316685 0.64826447 0.83727574]
 [0.84070875 0.07653612 0.35842223]]


In [11]:
#Question 3c
array_3d = np.random.random((3, 3, 3))

intersection = array_3d[2, 0, 2] 
print("3-D Array (3x3x3):")
print(array_3d)
print("Intersection of the first row and third column in the third 2-D array:")
print(intersection)

3-D Array (3x3x3):
[[[0.89000437 0.21469387 0.68440887]
  [0.06906949 0.3249128  0.99381426]
  [0.81441902 0.59356474 0.83609476]]

 [[0.04012948 0.83063397 0.34241841]
  [0.0019633  0.62306162 0.9989526 ]
  [0.97942634 0.31135945 0.75493885]]

 [[0.94778529 0.59962769 0.67863633]
  [0.40670591 0.05186814 0.79738357]
  [0.56783047 0.98421624 0.79825958]]]
Intersection of the first row and third column in the third 2-D array:
0.6786363325513368


In [13]:
#Question 4a
import numpy as np

array_2d = np.random.randint(1, 101, size=(5, 4))

print("Original Array:")
print(array_2d)

even_numbers = array_2d[array_2d % 2 == 0]

print("Even Numbers:")
print(even_numbers)

Original Array:
[[100  95  64  64]
 [ 80  96  37  87]
 [ 92   5  11  13]
 [ 31  38  57  26]
 [ 14  82  19  46]]
Even Numbers:
[100  64  64  80  96  92  38  26  14  82  46]


In [15]:
#Question 4b
import numpy as np

array_2d = np.random.randint(1, 101, size=(5, 4))
print("Original Array:")
print(array_2d)

odd_numbers = array_2d[array_2d % 2 != 0]

print("Odd Numbers:")
print(odd_numbers)

Original Array:
[[75 72 19 24]
 [39 55 40 75]
 [ 6 68 99 64]
 [84 68 75  4]
 [21  5 12 47]]
Odd Numbers:
[75 19 39 55 75 99 75 21  5 47]


In [17]:
#Question 4c
import numpy as np

array_2d = np.random.randint(1, 101, size=(5, 4))

print("Original Array:")
print(array_2d)

row_wise_sum = np.sum(array_2d, axis=1)

print("Row-wise Sum of All Elements:")
print(row_wise_sum)

Original Array:
[[97 66 55 36]
 [ 9 63 68 15]
 [42 93 80  8]
 [93 62 26 76]
 [78 95 63 21]]
Row-wise Sum of All Elements:
[254 155 223 257 257]


In [19]:
#Question 4d
import numpy as np

array_2d = np.random.randint(1, 101, size=(5, 4))

print("Original Array:")
print(array_2d)

column_wise_sum = np.sum(array_2d, axis=0)

print("Column-wise Sum of All Elements:")
print(column_wise_sum)

Original Array:
[[11 78 62 84]
 [99 80 31 36]
 [35  6 98 11]
 [50 88 85 24]
 [36  3 36 99]]
Column-wise Sum of All Elements:
[231 255 312 254]


In [21]:
#Question 4e
import numpy as np
array_2d = np.random.randint(1, 101, size=(5, 4))
print("Original 2-D Array:")
print(array_2d)
array_3d = array_2d.reshape(2, 2, 5)

print("Reshaped 3-D Array (2x2x5):")
print(array_3d)

Original 2-D Array:
[[43 23 79 37]
 [18 90 59  8]
 [90 27 88 77]
 [90 43 19 89]
 [31 61 30 71]]
Reshaped 3-D Array (2x2x5):
[[[43 23 79 37 18]
  [90 59  8 90 27]]

 [[88 77 90 43 19]
  [89 31 61 30 71]]]


In [23]:
#Question 5a
import numpy as np
array_2d = np.random.randint(1, 101, size=(5, 4))
print("Original Array:")
print(array_2d)
array_2d[[0, 2]] = array_2d[[2, 0]]
print("Array After Swapping First and Third Rows:")
print(array_2d)

Original Array:
[[ 58  65  44  15]
 [ 45  60  20  89]
 [ 63  73  86   8]
 [ 13  39  26  84]
 [100  19   1  29]]
Array After Swapping First and Third Rows:
[[ 63  73  86   8]
 [ 45  60  20  89]
 [ 58  65  44  15]
 [ 13  39  26  84]
 [100  19   1  29]]


In [25]:
#Question 5b
import numpy as np
array_2d = np.random.randint(1, 101, size=(5, 4))
print("Original Array:")
print(array_2d)
array_2d[:, [1, 3]] = array_2d[:, [3, 1]]
print("Array After Swapping Second and Fourth Columns:")
print(array_2d)

Original Array:
[[76 64 47 61]
 [ 2 37 53 62]
 [54 61 97 59]
 [89 59 82 85]
 [93 34 23 92]]
Array After Swapping Second and Fourth Columns:
[[76 61 47 64]
 [ 2 62 53 37]
 [54 59 97 61]
 [89 85 82 59]
 [93 92 23 34]]


In [27]:
#Question 5c
import numpy as np
array_2d = np.random.randint(1, 101, size=(5, 4))
print("Original Array:")
print(array_2d)
array_2d[array_2d < 50] = 0
print("Array After Replacing Values Less Than 50 with Zero:")
print(array_2d)

Original Array:
[[28 99 55 11]
 [14 18 70 21]
 [87 31 37 81]
 [64 38 17 35]
 [45 88 31 11]]
Array After Replacing Values Less Than 50 with Zero:
[[ 0 99 55  0]
 [ 0  0 70  0]
 [87  0  0 81]
 [64  0  0  0]
 [ 0 88  0  0]]


In [29]:
#Question 5d
import numpy as np
array_2d = np.random.randint(1, 101, size=(5, 4))
print("Original 2-D Array:")
print(array_2d)
array_1d = array_2d.flatten()  # or use array_2d.ravel()
print("Converted 1-D Array:")
print(array_1d)

Original 2-D Array:
[[91 33 66 23]
 [69 56 63  9]
 [18 60 36 48]
 [19 85 82 69]
 [64 75 65 46]]
Converted 1-D Array:
[91 33 66 23 69 56 63  9 18 60 36 48 19 85 82 69 64 75 65 46]


In [31]:
#Question 6
#Stacking in NumPy refers to the process of joining multiple arrays along a new axis. It allows you to combine arrays in a way that results in a higher-dimensional array.

import numpy as np

# Create two 1-D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked = np.stack((a, b))
print("Stacked Array (np.stack):")
print(stacked)

Stacked Array (np.stack):
[[1 2 3]
 [4 5 6]]


In [ ]:
#Question 6 Difference between the two
# 1. Stacking: Joins arrays along a new axis, increasing dimensionality.
Concatenation: Joins arrays along an existing axis, keeping the same dimensionality.
# 2. Stacking uses functions like np.stack, np.vstack, np.hstack, and np.dstack.
Concatenation uses the np.concatenate function.
# 3. Stacking can increase the dimensionality of the result. For example, stacking two 1-D arrays results in a 2-D array.
Concatenation keeps the same number of dimensions. For example, concatenating two 1-D arrays will still yield a 1-D array