In [2]:
'''Q1. Create the first numpy array of 1-D with values (1,2,3,0).
 Create a second numpy array of 1-D with values (4,1,0,
 6). Perform following simple arithme�c opera�ons on
 these two numpy arrays:
 • Addi�on
 • Subtrac�on
 • Mul�plica�on
 • Division'''

import numpy as np
arr1=np.array([1,2,3,0])
arr2=np.array([4,1,0,6])

add=arr1+arr2 #addition
sub=arr1-arr2 #subtraction
multi=arr1*arr2 #multiplication
div=arr1/arr2 #division

print("addition :",add)
print("subtraction :",sub)
print("multiplication :",multi)
print("divison :",div)



addition : [5 3 3 6]
subtraction : [-3  1  3 -6]
multiplication : [4 2 0 0]
divisoin : [0.25 2.    inf 0.  ]


<ipython-input-2-5faf80906408>:17: RuntimeWarning: divide by zero encountered in divide
  div=arr1/arr2 #division


In [4]:
'''Q2. Create the first numpy array of random integers
 between 1-100 of 5 elements in 1-D. Create second
 numpy array of 2-D for the same range of integers of
 shape 4*5. Now perform following simple arithme�c
 opera�ons on these two numpy arrays:
 • Addi�on
 • Subtrac�on'''

import numpy as np
arr1=np.random.randint(1,100,(5))
arr2=np.random.randint(1,100,(4,5))
add=arr1+arr2 #addition
print("Addition :\n",add)
sub=arr1-arr2 #subtraction
print("Subtraction :\n",sub)





Addition :
 [[146 102  39  57 179]
 [122 124  62 102 185]
 [150  49  50 100 104]
 [ 95 116 108  59 125]]
Subtraction :
 [[ 24 -46  33 -15  -1]
 [ 48 -68  10 -60  -7]
 [ 20   7  22 -58  74]
 [ 75 -60 -36 -17  53]]


In [26]:
'''Q3. Create a 3-D array of 27 random elements using random
 func�on of shape 3*3*3. Now pull the following
 elements using indexing/slicing
 • Third column of second 2-D array
 • First and third row of first 2-D array
 • Intersec�on of first row and third column in
 third 2-D aray'''

arr=np.random.randint(1,100,(3,3,3))
print(arr,"\n\n")
print(arr[1,:,2])#Third column of second 2-D array
print(arr[0,0::2,:])# First and third row of first 2-D array
print(np.intersect1d(arr[2,0,:],arr[2,:,2]))#Intersecton of first row and third column in third 2-D array




[[[30 55 88]
  [98 63 88]
  [56 22 50]]

 [[21 93 75]
  [46 30 38]
  [54 60 54]]

 [[93 60 78]
  [55 99 11]
  [97 23 96]]] 


[75 38 54]
[[30 55 88]
 [56 22 50]]
[78]


In [33]:
'''Q4. Create a 2-D numpy array of random integers between
 1 to 100 with shape 5*4. Now perform following
 opera�ons:
 • Print only the even numbers from this array
 • Print only the odd numbers from this array
 • Print row wise sum of all elements
 • Print column wise sum of all elements
 • Convert this 2-D array into 3-D array of shape
 2*2*5'''

arr=np.random.randint(1,100,(5,4))
print(arr[arr%2==0]) #Print only the even numbers from this array
print(arr[~arr%2==0]) #Print only the odd numbers from this array
print(np.sum(arr,axis=1)) #Print row wise sum of all elements
print(np.sum(arr,axis=0)) #Print colomn wise sum of all elements
Arr_3D=arr.reshape(2,2,5)
print(Arr_3D)




[20 96 50 42 52 60 92 20 22 18]
[13 47 37 41 69 63 53 63 11 69]
[176 170 224 207 161]
[187 228 294 229]
[[[13 47 20 96 37]
  [41 50 42 52 60]]

 [[92 20 22 69 63]
  [53 63 11 69 18]]]


In [45]:
'''Q5. Create a 2-D numpy array of random integers between
 1 to 100 with shape 5*4. Now perform following
 opera�ons:
 • Swap first row with third row
 • Swap second column with fourth column.
 • Replace the values less than 50 with zero.
 • Convert this 2D array into 1-D array'''

arr=np.random.randint(1,100,(5,4))
arr[[0,2]]=arr[[2,0]] #Swap first row with third row
arr[:,[1,3]]=arr[:,[3,1]] #Swap second column with fourth column.
arr[arr<50]=0 #Replace the values less than 50 with zero.
np.flatten(arr) #Convert this 2D array into 1-D array




array([[26, 72, 39, 91],
       [22, 74, 95, 30],
       [52, 62, 55, 80],
       [ 3, 44, 35, 68],
       [25, 74, 57, 47]])

In [2]:
'''Q6. Explain the concept of stacking in numpy with examples.
 How is it different from concatena�on. Give any 3
 differences between them.

 Ans. Stacking in NumPy combines arrays along a new axis, increasing dimensionality. For instance, np.stack((arr1, arr2), axis=0) stacks arrays vertically, while np.hstack and np.vstack stack along existing dimensions.

Concatenation, on the other hand, joins arrays along an existing axis, keeping the dimensionality unchanged. For example, np.concatenate((arr1, arr2), axis=0) appends arrays row-wise or column-wise without introducing new dimensions.

Differences
Axis: Stacking adds a new axis; concatenation uses an existing one.
Dimensionality: Stacking increases it; concatenation doesn't.
Functions: Stacking uses np.stack, np.hstack; concatenation uses np.concatenate.'''

"Q6. Explain the concept of stacking in numpy with examples.\n How is it different from concatena�on. Give any 3\n differences between them.\n\n Ans. Stacking in NumPy combines arrays along a new axis, increasing dimensionality. For instance, np.stack((arr1, arr2), axis=0) stacks arrays vertically, while np.hstack and np.vstack stack along existing dimensions.\n\nConcatenation, on the other hand, joins arrays along an existing axis, keeping the dimensionality unchanged. For example, np.concatenate((arr1, arr2), axis=0) appends arrays row-wise or column-wise without introducing new dimensions.\n\nDifferences\nAxis: Stacking adds a new axis; concatenation uses an existing one.\nDimensionality: Stacking increases it; concatenation doesn't.\nFunctions: Stacking uses np.stack, np.hstack; concatenation uses np.concatenate."