## Name: Raghul Khanna

In [8]:
import numpy as np

### Q1.Create the first numpy array of 1-D with values (1,2,3,0).
###  Create a second numpy array of 1-D with values (4,1,0,
###  6). Perform following simple arithmetic operations on
###  these two numpy arrays:
###  • Addition
###  • Subtraction
###  • Multplication
###  • Division

In [9]:
arr1 = np.array([1, 2, 3, 0])
arr2 = np.array([4, 1, 0, 6])
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2

with np.errstate(divide='ignore', invalid='ignore'):
    division = arr1 / arr2 
    division[np.isnan(division)] = 0 

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [5 3 3 6]
Subtraction: [-3  1  3 -6]
Multiplication: [4 2 0 0]
Division: [0.25 2.    inf 0.  ]


### Q2. Create the first numpy array of random integers
###  between 1-100 of 5 elements in 1-D. Create second
###  numpy array of 2-D for the same range of integers of
###  shape 4*5. Now perform following simple arithmetic
###  operations on these two numpy arrays:
###  • Addition
###  • Subtraction


In [10]:
arr1 = np.random.randint(1, 101, 5)
arr2 = np.random.randint(1, 101, (4, 5))
addition = arr2 + arr1  
subtraction = arr2 - arr1 

print("1-D Array (arr1):", arr1)
print("2-D Array (arr2):\n", arr2)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)

1-D Array (arr1): [31  4 82 88 43]
2-D Array (arr2):
 [[82 43 67 39 42]
 [ 8 58 44 51 26]
 [43 33 13  1 89]
 [57 49 89 69 23]]

Addition:
 [[113  47 149 127  85]
 [ 39  62 126 139  69]
 [ 74  37  95  89 132]
 [ 88  53 171 157  66]]

Subtraction:
 [[ 51  39 -15 -49  -1]
 [-23  54 -38 -37 -17]
 [ 12  29 -69 -87  46]
 [ 26  45   7 -19 -20]]


### Q3. Create a 3-D array of 27 random elements using random
###  function of shape 3*3*3. Now pull the following
###  elements using indexing/slicing
###  • Third column of second 2-D array
###  • First and third row of first 2-D array
###  • Intersection of first row and third column in
###  third 2-D aray

In [11]:
arr_3D = np.random.randint(1, 101, (3, 3, 3))
third_column_second_2D = arr_3D[1, :, 2]
first_and_third_row_first_2D = arr_3D[0, [0, 2], :]
intersection = arr_3D[2, 0, 2]

print("3-D Array:\n", arr_3D)
print("\nThird column of the second 2-D array:\n", third_column_second_2D)
print("\nFirst and third row of the first 2-D array:\n", first_and_third_row_first_2D)
print("\nIntersection of the first row and third column in the third 2-D array:\n", intersection)

3-D Array:
 [[[95 38 38]
  [12 78 23]
  [52 17 80]]

 [[47  8 17]
  [78 46 91]
  [ 2 34 67]]

 [[ 8 98 87]
  [56 44 93]
  [46 53  7]]]

Third column of the second 2-D array:
 [17 91 67]

First and third row of the first 2-D array:
 [[95 38 38]
 [52 17 80]]

Intersection of the first row and third column in the third 2-D array:
 87


### Q4. Create a 2-D numpy array of random integers between
###  1 to 100 with shape 5*4. Now perform following
###  operations:
###  • Print only the even numbers from this array
###  • Print only the odd numbers from this array
###  • Print row wise sum of all elements
###  • Print column wise sum of all elements
###  • Convert this 2-D array into 3-D array of shape
###  2*2*5 

In [12]:
import numpy as np

arr_2D = np.random.randint(1, 101, (5, 4))
even = arr_2D[arr_2D % 2 == 0]
odd = arr_2D[arr_2D % 2 != 0]
row_wise_sum = np.sum(arr_2D, axis=1)
column_wise_sum = np.sum(arr_2D, axis=0)
arr_3D = arr_2D.reshape(2, 2, 5)

print("Original 2-D Array:\n", arr_2D)
print("\nEven Numbers:\n", even)
print("\nOdd Numbers:\n", odd)
print("\nRow-wise Sum of Elements:\n", row_wise_sum)
print("\nColumn-wise Sum of Elements:\n", column_wise_sum)
print("\n3-D Array (2x2x5):\n", arr_3D)

Original 2-D Array:
 [[ 4 99  7  6]
 [69 95 76 34]
 [36 75 64 59]
 [17 46 28 68]
 [88 31 27 47]]

Even Numbers:
 [ 4  6 76 34 36 64 46 28 68 88]

Odd Numbers:
 [99  7 69 95 75 59 17 31 27 47]

Row-wise Sum of Elements:
 [116 274 234 159 193]

Column-wise Sum of Elements:
 [214 346 202 214]

3-D Array (2x2x5):
 [[[ 4 99  7  6 69]
  [95 76 34 36 75]]

 [[64 59 17 46 28]
  [68 88 31 27 47]]]


### Q5. Create a 2-D numpy array of random integers between
###  1 to 100 with shape 5*4. Now perform following
###  operations:
###  • Swap first row with third row
###  • Swap second column with fourth column.
###  • Replace the values less than 50 with zero.
###  • Convert this 2D array into 1-D array

In [13]:
arr_2D = np.random.randint(1, 101, (5, 4))
arr_2D[[0, 2]] = arr_2D[[2, 0]]
arr_2D[:, [1, 3]] = arr_2D[:, [3, 1]]
arr_2D[arr_2D < 50] = 0
arr_1D = arr_2D.flatten()

print("Array after swapping first row with third row:\n", arr_2D)
print("\n2-D Array second column with fourth column:\n", arr_2D)
print("\n2-D Array with Values Less Than 50 Replaced by Zero:\n", arr_2D)
print("\nConverted 1-D Array:\n", arr_1D)

Array after swapping first row with third row:
 [[ 0 87  0 71]
 [ 0 66  0 84]
 [92 55 85  0]
 [ 0 51  0 96]
 [67 78  0 94]]

2-D Array second column with fourth column:
 [[ 0 87  0 71]
 [ 0 66  0 84]
 [92 55 85  0]
 [ 0 51  0 96]
 [67 78  0 94]]

2-D Array with Values Less Than 50 Replaced by Zero:
 [[ 0 87  0 71]
 [ 0 66  0 84]
 [92 55 85  0]
 [ 0 51  0 96]
 [67 78  0 94]]

Converted 1-D Array:
 [ 0 87  0 71  0 66  0 84 92 55 85  0  0 51  0 96 67 78  0 94]


### Q6. Explain the concept of stacking in numpy with examples.
###  How is it different from concatenation. Give any 3
###  differences between them.


##### Stacking helps in joining multiple arrays. It joins arrays of same dimension. Stacking is done alone new axis.
##### 3 differences between stacking and concatenation;
##### i. Concatenation joins multiple arrays but along an existing axis.
##### ii.  It does not create a new dimension.
##### iii. Function used is np.concatenate().

In [14]:
# Examples of stacking
# 1. Vertical stacking

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack([arr1, arr2])
print("Vertical Stacking:\n", result)

Vertical Stacking:
 [[1 2 3]
 [4 5 6]]


In [15]:
# 2. Horizontal stacking

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack([arr1, arr2])
print("Horizontal Stacking:\n", result)

Horizontal Stacking:
 [1 2 3 4 5 6]


In [16]:
# Depth stacking

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.dstack([arr1, arr2])
print("Depth Stacking (dstack):\n", result)

Depth Stacking (dstack):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
